### ISSUE TITLE
ZeroDivisionError when g2 is 0

### ISSUE THREAD

**Issue by Pantamis** [stla/pyweierstrass#2]
Hi !

When running `_half_periods(0, 1)` I get the following:

```
/path/pyweierstrass/pyweierstrass/weierstrass.py, line 80, in _half_periods
    j = 1728 / (1 - 27*g3*g3/g2cube)
ZeroDivisionError: division by zero
```

It seems that your implementation doesn't support curve with a zero j-invariant because of this. It is weird because when I try to add a check with simple if branch in case g2 is zero to set j = 0 it also complain about a zero division I don't get it honestly :')

I also found your other gists ([this one](https://gist.github.com/stla/d771e0a8c351d16d186c79bc838b6c48)) and it seems to work with g2 = 0 however it seems the half periods are not right (when g3 is not set to 1 the functions have period 1.53 which should not be the case...) .

Thanks for your work !

**Comment by stla** [comment]
Hello,

Thank you for the report. 

This should work by multiplying both the numerator and the denominator by `g2cube`. I'll check and update. I'll inform you.

**Comment by stla** [comment]
Hmm there are two other difficulties. The `kleinjinv` function yields a division by zero for `z=0`. I solved this problem. But then there's a division 0/0 in `_half_periods`. Didn't solve that yet.

**Comment by stla** [comment]
Ah nice !! The solution is given here: <https://mathworld.wolfram.com/Omega-2Constant.html>!

**Comment by stla** [comment]
That's done. Thanks again for the report.

**Comment by Pantamis** [comment]
Hi !

Thanks for handling this so quickly !

Indeed I checked the same page for the equianharmonic case !

I saw you made a special case when g2 = 0 and g3 = 1 so this return the same error when g2 =0 but g3 is not 1 :/

I think it should be possible to handle all the possible case using that g3 is homogeneous of degree -6: g3(lambda w1, lambda w2) = lambda^(-6) g3(w1, w2) [ref](https://en.wikipedia.org/wiki/Weierstrass_elliptic_function#Invariants)

If I am not mistaken, this implies that when g3 = z (not zero else its not elliptic) and g2 =0 then the half periods are lambda w1, lambda w2 with lambda = z^(-1/6) and w1, w2 given by your reference.

This should allow you to return half-periods in all cases ?

**Comment by stla** [comment]
It's past midnight here ^^ I"ll take a look tomorrow.

**Comment by stla** [comment]
I've checked. You are right :+1: Gonna implement.

**Comment by HeskethGD** [comment]
For the case where g2=0 the fix has:
`g3^(-1/6)`
This should be:
`g3 ** (-1/6)`

These do different things in Python

**Comment by stla** [comment]
Argh ! Thank you.
