### ISSUE TITLE
Incorrect half-periods formula leading to wrong sign for g3 when calculated from half-periods

### ISSUE THREAD

**Issue by HeskethGD** [stla/pyweierstrass#3]
- The series for g2 in terms of G4 is quartic in omega1. When solving for omega1 in terms of g2 the result is thus only determined up to a quartic root of unity.
- Because the result for omega1 can thus sometimes be incorrectly multiplied by +1, -1, +i, or -i, we can observe errors when trying to recalculate g2 and g3 from omega and the mistake manifests as giving the wrong sign for g3.
- One solution is to include the series for g3 in terms of G6 to decide whether to multiply the periods by the imaginary unit or not, then the periods are defined up to a sign +/-1. In other words, the ratio g2/g3 is quadratic in the half-periods not quartic.
- As the half periods are only defined up to a sign because of periodicity anyway this suffices and elliminates the problem of obtaining the wrong sign for g3 when calculating from omega.
- By G4 and G6 we mean G4(1, tau), G6(1, tau) with G_2k(tau) = 2 * zeta(2*k) * E_2k(tau), with zeta the Riemann zeta function and E the Eisenstein series expressible in terms of theta functions
- A single example of how the original method for calculating the half-periods can fail is given below as g3 takes the wrong sign:

```
# Input values of g2 and g3 are chosen
g2_num =  mpc(real='-73.4914329314137', imag='95.8413827483826')
g3_num =  mpc(real='54.2026055822565', imag='27.1486316597472')

# The values for g2 and g3 are then calculated from omega1 and omega2
# and the values for omega1 and omeg2 are themselves calculated from the original g2 g3
# This should return the original values but it returns -g3 instead
g_from_omega(*omega_from_g(g2_num, g3_num))

Output:
(mpc(real='-73.491432931413684', imag='95.841382748382628'),
 mpc(real='-54.202605582253817', imag='-27.14863165974365'))
```

So instead of doing this:
$\displaystyle g_{2} = \frac{15 G_{4}}{4 \omega_{1}^{4}}$
$\displaystyle \omega_{1} = \sqrt[4]{\frac{15G_{4}}{4g_{2}}}$

perhaps the following would work better:
$\displaystyle g_{2} = \frac{15 G_{4}}{4 \omega_{1}^{4}}$
$\displaystyle g_{3} = \frac{35 G_{6}}{16 \omega_{1}^{6}}$
$\displaystyle \frac{g_{2}}{g_{3}} = \frac{12 G_{4} \omega_{1}^{2}}{7 G_{6}}$
$\displaystyle \omega_{1} = \sqrt{\frac{7G_{6} g_{2}}{12G_{4} g_{3}}}$

I have been exploring this here: https://github.com/HeskethGD/Elliptic-Functions/tree/master/numerical_evaluation
There are some numerical tests and a suggested modification that implements the above.
Thanks again for your efforts on this.

**Comment by stla** [comment]
Thanks! I will take a look more carefully and do the change tomorrow.

**Comment by stla** [comment]
Tested with my R package. Unit tests OK :+1:

**Comment by stla** [comment]
I've finally done the change. Thanks again!

**Comment by HeskethGD** [comment]
Great thanks that works!

**Comment by stla** [comment]
However this formula fails in the case `g3=0`. So I kept the old formula for this case (I've just pushed one minute ago).

**Comment by HeskethGD** [comment]
ok
